name: flutter_template
description: Template project for starting new Flutter projects by @codaveto.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Data
  hive: ^2.1.0
  json_annotation: ^4.4.0
  json_serializable: ^6.1.6

  # Firebase
  firebase_core: ^1.15.0
  firebase_auth: ^3.3.15
  cloud_firestore: ^3.1.13
  firebase_analytics: ^9.1.6
  firebase_crashlytics: ^2.6.3

  # Http
  chopper: ^4.0.5
  url_launcher: ^6.1.0

  # UI
  flutter_svg: ^1.0.3
  overlay_support: 1.2.1

  # Util
  get_it: ^7.2.0
  intl_utils: ^2.6.1
  loglytics: ^0.10.2+2
  flutter_dotenv: ^5.0.2
  connectivity_plus: ^2.3.0
  permission_handler: ^9.2.0
  flutter_form_builder: 7.1.1
  form_builder_validators: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.1.0
  build_runner: ^2.1.10
  chopper_generator: ^4.0.5
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
          weight: 200
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Italic.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito-BlackItalic.ttf
          weight: 900

flutter_intl:
  enabled: true
  class_name: Strings
  main_locale: "nl"
  arb_dir: lib/strings
  output_dir: lib/strings/generated
